name: eco_wallet
description: A Financial Management App built with Clean Architecture and BLoC.
publish_to: 'none' 
version: 1.0.6+5

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  fpdart: ^1.2.0
  equatable: ^2.0.7
  path_provider: ^2.1.5
  path: ^1.9.1
  google_fonts: ^6.3.3
  intl: ^0.20.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  drift_dev: ^2.30.0
  injectable_generator: ^2.9.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  generate: true

# see https://flutter.dev/to/font-from-package
